url: https://alittleq.github.io/

#comment out when push to github
baseurl: /HeyYZU_Web

# Site settings
title: HeyYZU
# email:
description: YZU Portal in your pocket.


# Team names, titles and social links
peopleRow1:
- name: Erickson Juang
  pic: 7bc81b728640a4917ec3b6625d16425e
  position: Project Manager & Back-end Developer
  social:
    - title: facebook
      url: https://fb.me/ChuangPingLuen
    - title: github
      url: https://github.com/bingluen
    - title: linkedin
      url: https://tw.linkedin.com/in/bingluen
    - title: home
      url: http://bingluen.tw

- name: Ren Chen
  pic: 9ae1e97f3759b8c4d453b7a006b74770
  position: UI / UX Designer
  social:
    - title: github
      url: https://github.com/m9731526

peopleRow2:
- name: Wu Guan Xian
  pic: 13570825e48880d1a13e0a2f228cf338
  position: Android Developer
  social:
    - title: facebook
      url: https://fb.me/eric0324
    - title: github
      url: https://github.com/eric0324
    - title: linkedin
      url: https://tw.linkedin.com/in/eric0324
    - title: home
      url: https://eircwu.asia

- name: Andy Chean
  pic: c38947a608327a0d657e09df7e193bb0
  position: iOS Developer
  social:
    - title: facebook
      url: https://fb.me/chenkaijia
    - title: github
      url: https://github.com/singbird81

- name: ALitTLeQ
  pic: 47419b6d30fa3c1cb5d96dc0cfc5657a
  position: Python / Website Developer
  social:
    - title: facebook
      url: https://fb.me/ALittleQ.Wang
    - title: github
      url: https://github.com/ALitTLeQ

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
